### ISSUE TITLE
Feature request: apply uglifyjs to optimized build

### ISSUE THREAD

**Issue by rtxm** [allo-media/elm-kitchen#13]
By following the advice at https://guide.elm-lang.org/optimization/asset_size.html we can get very impressive minification of the resulting JS file.

For example, on a project of mine, using the script on the linked page above:
```
Compiled size:165767 bytes  (public/app.js)
Minified size:36621 bytes  (public/app.min.js)

```

**Comment by n1k0** [comment]
Haha it's funny we dropped it in elm-kitchen while we're still using it in all our AM projects :) thanks for the report, will readd soon.

**Comment by n1k0** [comment]
v3.2.0 released and published to the npm repository.
