### ISSUE TITLE
Split encoder and decoders out of Data.Session

### ISSUE THREAD

**Issue by Natim** [allo-media/elm-kitchen#22]
I would rather have

Encoder/Session.elm and Decoder/Session.elm with Decoder/Store.elm

I guess you could told me that I can do it in my project, but it would set a nice track for people not to end-up with a Data/Session.elm file with 2000 lines of code in it.

**Comment by n1k0** [comment]
The main issue here is that we don't have enough code in the skeleton to justify such a split; maybe what we want is some documentation...

**Comment by Natim** [comment]
I tried and it doesn't seems to be indecent in terms of code. See #24

**Comment by karantan** [comment]
> I'd rather have some How to grow an elm-kitchen app documentation in the wiki with tips like this one.

Should we start doing this? Maybe for start just add things to README.md. I can help with this.

**Comment by n1k0** [comment]
@karantan that'd be cool!

The idea which worked great for us is to store encoders and decoders in each entity module. For example, if you have a `Data.User` module, you can expose `encode` and `decode` functions, as well as other helpers manipulating this specific data structure. This is kind of a business domain driven code organization, vs. a more technically specialized one.

Here's a sample data module we have in our main app:

```elm
module Data.Qualification exposing (Qualification, decode, encode)

import Data.Label as Label exposing (Label)
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type alias Qualification =
    { decisional : Label
    , contextual : List Label
    }


decode : Decoder Qualification
decode =
    Decode.map2 Qualification
        (Decode.field "decisional" Label.decode)
        (Decode.field "contextual" (Decode.list Label.decode))


encode : Qualification -> Encode.Value
encode { decisional, contextual } =
    Encode.object
        [ ( "decisional", Label.encode decisional )
        , ( "contextual", Encode.list Label.encode contextual )
        ]
```

As you can see here, this module depends on the encoders and decoders from the `Data.Label` module, which makes it clear how they work together.

**Comment by merwan** [comment]
Project is now deprecated #50
