### ISSUE TITLE
Move to Github Templates

### ISSUE THREAD

**Issue by n1k0** [allo-media/elm-kitchen#28]
Now Github supports [template repos](https://help.github.com/en/articles/creating-a-template-repository), and as elm-kitchen is basically a project template, we may want to just make this repository a template.

Main question is should we keep the npm package?

**Comment by Natim** [comment]
I guess you can try a create a template from it and we will see if it works as well as the cli tool. In my workflow I don't create a github project per elm-kitchen project.

**Comment by n1k0** [comment]
Yeah we may want to keep the CLI tool anyway. If we enable this repo as a template, we'll have to revamp its structure though, as the template currently lives in the `skeleton` subdirectory. I'm gonna study how similar template-based projects do.

**Comment by n1k0** [comment]
Ok so the mainstream consensus seems to be using `npm init <initializer>` (or `yarn create <initializer>`) ([docs](https://docs.npmjs.com/cli/init#description)) to init a npm/yarn project based on a template.

That's how [elm-batteries](https://github.com/cedricss/elm-batteries) is doing (see [create-elm-batteries](https://www.npmjs.com/package/create-elm-batteries)), but it's not clear yet how you publish such `create-*` package to npm.

**Comment by merwan** [comment]
Project is now deprecated #50
