### ISSUE TITLE
Investigate using Parcel

### ISSUE THREAD

**Issue by n1k0** [allo-media/elm-kitchen#29]
More and more Elm projects are using [Parcel](https://parceljs.org/elm.html), which simplifies **a lot** setup and operations.

`elm-live` has proven being difficult to work with lately, especially with their latest 3.4.1 release which basically watches everything by default, including stuff in `node_modules` and so on, with no obvious way to alter this behavior in any way.

Let's investigate if Parcel is mature & feature complete enough to replace our current setup.

**Comment by karantan** [comment]
@n1k0 check my PR. I would love your input if you think anything should be done differently.

**Comment by merwan** [comment]
Project is now deprecated #50
