### ISSUE TITLE
Transfer of ownership?

### ISSUE THREAD

**Issue by merwan** [allo-media/elm-kitchen#50]
Hello @n1k0 @vjousse  @magopian @Natim @fbentz 
Would any one of you be interested in a transfer of ownership for this repository? Can this be of interest for the Elm community?

**Comment by n1k0** [comment]
Hi @merwan, thanks for asking, even if a bit late :D Since I've lost any write access to the repo 3 years ago, I've personally resolved to fork this tool as [elm-kitten](https://n1k0.github.io/elm-kitten/) which I'm now using & maintaining from there :)

**Comment by merwan** [comment]
Project is now [deprecated in the README](https://github.com/allo-media/elm-kitchen/blob/master/README.md#deprecated-elm-kitchen)
I'm now closing all open issues and pull requests

**Comment by merwan** [comment]
Thanks for your feedback @n1k0, too bad this project maintenance was not passed over sooner.
